AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: clv-system
  Environment:
    Type: String
    Default: dev
  FrontendCitizenBucket:
    Type: String
    Default: default
  GCaptchaSecret:
    Type: String
    Default: default
  TokenSecret:
    Type: String
    Default: default
Resources:

  DynamoDBCredDownload:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${ProjectName}-descarga
      AttributeDefinitions:
        - AttributeName: dni
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: dni
          KeyType: HASH
  
  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  CrudFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-${ProjectName}-CrudFunction
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        CreateItem:
          Type: Api
          Properties:
            Path: /items
            Method: POST
        GetItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: GET
        UpdateItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: PUT
        DeleteItem:
          Type: Api
          Properties:
            Path: /items/{id}
            Method: DELETE
